In [2]:
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

df_logs = pd.read_csv('/content/drive/MyDrive/PROJETOS_LOGS/labeled.csv', nrows=1000000)
df_logs.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,ip,time,method,url,protocol,status,size,referrer,user_agent,extra,no,label,type
0,31.56.96.51,2019-01-22 00:26:16+00:00,GET,/image/60844/productModel/200x200,HTTP/1.1,200,5667,https://www.zanbil.ir/m/filter/b113,Mozilla/5.0 (Linux; Android 6.0; ALE-L21 Build...,-,2,0,benign
1,31.56.96.51,2019-01-22 00:26:16+00:00,GET,/image/61474/productModel/200x200,HTTP/1.1,200,5379,https://www.zanbil.ir/m/filter/b113,Mozilla/5.0 (Linux; Android 6.0; ALE-L21 Build...,-,3,0,benign
2,91.99.72.15,2019-01-22 00:26:17+00:00,GET,/product/31893/62100/سشوار-خانگی-پرنسلی-مدل-PR...,HTTP/1.1,200,41483,-,Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:16...,-,5,0,benign
3,178.253.33.51,2019-01-22 00:26:19+00:00,GET,/m/product/32574/62991/ماشین-اصلاح-صورت-پرنسلی...,HTTP/1.1,200,20406,"https://www.zanbil.ir/m/filter/p5767,t156?name...",Mozilla/5.0 (Linux; Android 5.1; HTC Desire 72...,-,13,0,benign
4,91.99.72.15,2019-01-22 00:26:19+00:00,GET,/product/10075/13903/مایکروفر-رومیزی-سامسونگ-م...,HTTP/1.1,200,41725,-,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,-,15,0,benign

In [3]:
contagem_ataques = df_logs['type'].value_counts()
print(contagem_ataques)

type
benign      999822
bot            141
scanning        20
rce             17
Name: count, dtype: int64

**Análise de Risco e Filtragem: **
Lógica aplicada para isolar o tráfego não-humano (bots e scanners) e tentativas de execução remota de código (RCE). O objetivo é garantir a investigação ágil das anomalias que receberam o statos 200 (OK), e passaram pelas camadas iniciais de defesa da infraestrutura.

In [4]:
df_auditoria = df_logs[df_logs['type'] != 'benign']
df_auditoria[['ip', 'time', 'type', 'status']].head(10)

                   ip                       time type  status
236    216.244.66.248  2019-01-22 00:27:28+00:00  bot     301
238    216.244.66.248  2019-01-22 00:27:30+00:00  bot     200
1305     74.6.168.162  2019-01-22 00:32:46+00:00  bot     301
1306     74.6.168.162  2019-01-22 00:32:48+00:00  bot     200
2798   213.174.147.83  2019-01-22 00:43:08+00:00  bot     301
2799   213.174.147.83  2019-01-22 00:43:08+00:00  bot     200
3809     95.216.2.253  2019-01-22 00:49:39+00:00  bot     200
4410  207.241.231.165  2019-01-22 00:55:10+00:00  bot     301
5225   46.225.135.218  2019-01-22 01:02:10+00:00  bot     200
7359   216.244.66.248  2019-01-22 01:13:22+00:00  bot     301

In [5]:
df_auditoria.to_csv('relatorio_auditoria_ameacas.csv', index=False)
print('Relatório de evidências gerado com sucesso!')

Relatório de evidências gerado com sucesso!